# typed: false
# frozen_string_literal: true

# This file was generated by tower's release workflow. DO NOT EDIT.
class FfTower < Formula
  desc "project management for people and agents, built on fufu"
  homepage "https://github.com/tyler-johnson/tower"
  version "0.1.0"
  license "MIT"

  depends_on "tyler-johnson/tap/fufu"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tyler-johnson/tower/releases/download/v0.1.0/ff-tower_0.1.0_darwin_amd64.tar.gz"
      sha256 "f1bb7d48ddbcf01ffd28afebbc0fa21ab850ccb3b577b0998eae0f25f42da8ac"
    end
    if Hardware::CPU.arm?
      url "https://github.com/tyler-johnson/tower/releases/download/v0.1.0/ff-tower_0.1.0_darwin_arm64.tar.gz"
      sha256 "80e31707937e1b1aa608ce1219dc3bac7fef079556d5c25df77b5e9b0d933973"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/tower/releases/download/v0.1.0/ff-tower_0.1.0_linux_amd64.tar.gz"
      sha256 "e6047d98a5fce2f48d50e047ec893b37da04c7a3585a6d028dec5183ae22d285"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/tower/releases/download/v0.1.0/ff-tower_0.1.0_linux_arm64.tar.gz"
      sha256 "1b0792214e86715b4e8ae3c8880a75b606857cf9183fd3e123b7eab53f6d88d6"
    end
  end

  def install
    bin.install "ff-tower"
  end

  def caveats
    <<~EOS
      tower is reached through fufu's dispatch — the verb is:

        ff tower
    EOS
  end

  test do
    system bin/"ff-tower", "--version"
  end
end
