# typed: false
# frozen_string_literal: true

# This file was generated by fufu's release workflow. DO NOT EDIT.
class Fufu < Formula
  desc "jj's workflow on git's repository - the working tree is the open change"
  homepage "https://github.com/tyler-johnson/fufu"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.11.0/ff_0.11.0_darwin_amd64.tar.gz"
      sha256 "8e592bf98cf050dc04165eaf8d47b82bf6cbc5ba86f56f1c37f47a05d35a233e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.11.0/ff_0.11.0_darwin_arm64.tar.gz"
      sha256 "064770f2e8a3f77ec75721dd8d608b57abec72c7b0d687fc2721b2465a7891ed"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.11.0/ff_0.11.0_linux_amd64.tar.gz"
      sha256 "b4116232704ce95572d3bee8ada30b3795616bf13d5a36c8c3a6199699ae701b"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.11.0/ff_0.11.0_linux_arm64.tar.gz"
      sha256 "829903e61eadaa960dfd71e88c8de599203fe339490afe3d77969ff1dc379d30"
    end
  end

  def install
    bin.install "ff"
  end

  def caveats
    <<~EOS
      fufu only captures when something invokes it. Wire the triggers:

        ff hook shell install          # alias git='ff git' in your shell rc
        ff hook agent install claude   # capture around Claude Code's tool actions
    EOS
  end

  test do
    system bin/"ff", "--version"
  end
end
