# typed: false
# frozen_string_literal: true

# This file was generated by fufu's release workflow. DO NOT EDIT.
class Fufu < Formula
  desc "jj's workflow on git's repository - the working tree is the open change"
  homepage "https://github.com/tyler-johnson/fufu"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.9.0/ff_0.9.0_darwin_amd64.tar.gz"
      sha256 "9a813be161fd69037baa2970ede5fae76cdea180da95173aebca67096ecb56fb"
    end
    if Hardware::CPU.arm?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.9.0/ff_0.9.0_darwin_arm64.tar.gz"
      sha256 "c80c40afab089f8c8ce1f4c5f91d0807f2ae034dce186662160405af73e58a54"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.9.0/ff_0.9.0_linux_amd64.tar.gz"
      sha256 "5b4072a041b91dc78b538b8cb6382febc9ed364a426ef46483a8746dcd65750f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.9.0/ff_0.9.0_linux_arm64.tar.gz"
      sha256 "5dfe594bf4d1c2add98f09108ccc3ba0fe7fc5f17534e44b4466ff4a1883085b"
    end
  end

  def install
    bin.install "ff"
  end

  def caveats
    <<~EOS
      fufu only captures when something invokes it. Wire the triggers:

        ff hook shell install          # alias git='ff git' in your shell rc
        ff hook agent install claude   # capture around Claude Code's tool actions
    EOS
  end

  test do
    system bin/"ff", "--version"
  end
end
