# typed: false
# frozen_string_literal: true

# This file was generated by fufu's release workflow. DO NOT EDIT.
class Fufu < Formula
  desc "jj's workflow on git's repository - the working tree is the open change"
  homepage "https://github.com/tyler-johnson/fufu"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.7.0/ff_0.7.0_darwin_amd64.tar.gz"
      sha256 "d3388f94c5147efb604da662c280da3adb7db7b96f473d86bf8316e98514e418"
    end
    if Hardware::CPU.arm?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.7.0/ff_0.7.0_darwin_arm64.tar.gz"
      sha256 "de7de9ebbced17bd7a522b6600a66796d017716de115061113cd6c882db0210d"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.7.0/ff_0.7.0_linux_amd64.tar.gz"
      sha256 "784af6d889ca463a607ad195cc983f09cc281e42853a410b88e517dfd19e65c0"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/fufu/releases/download/v0.7.0/ff_0.7.0_linux_arm64.tar.gz"
      sha256 "dd81c30fd0cf34923175bb0168be62032b341d445f5eb5b898e802af29abeff4"
    end
  end

  def install
    bin.install "ff"
  end

  def caveats
    <<~EOS
      fufu only captures when something invokes it. Wire the triggers:

        ff hook shell install          # alias git='ff git' in your shell rc
        ff hook agent install claude   # capture around Claude Code's tool actions
    EOS
  end

  test do
    system bin/"ff", "--version"
  end
end
