# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jog < Formula
  desc "Memory for your working tree - automatic git snapshots, jj-style"
  homepage "https://github.com/tyler-johnson/jog"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.7.0/jog_1.7.0_darwin_amd64.tar.gz"
      sha256 "80a6df05cf7bbd7e91d43e7f44aa696ecc76488cb059c8c75093249edf66925d"

      define_method(:install) do
        bin.install "jog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.7.0/jog_1.7.0_darwin_arm64.tar.gz"
      sha256 "836f186f3c3790fe8823fce890286d2c928a87d6e2803d20aefba0e02e34e2bd"

      define_method(:install) do
        bin.install "jog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.7.0/jog_1.7.0_linux_amd64.tar.gz"
      sha256 "caa230ec3f2f6968409672ec5bb1ff423d8e4406b0ccae3f2fe21dc43f344ce5"
      define_method(:install) do
        bin.install "jog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.7.0/jog_1.7.0_linux_arm64.tar.gz"
      sha256 "e9b7b3ecb5c65632932ac09d12c9a4aac87bf381df0a130932f1f14a5cb3f5fe"
      define_method(:install) do
        bin.install "jog"
      end
    end
  end

  def caveats
    <<~EOS
      jog only snapshots when something invokes it. Wire the triggers:

        jog install    # guided: the git alias, agent hooks, editor hooks

      or piece by piece: jog shell install, jog agents install,
      jog editors install <editor>. Then verify with:  jog doctor
    EOS
  end

  test do
    system bin/"jog", "version"
  end
end
