# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jog < Formula
  desc "Memory for your working tree - automatic git snapshots, jj-style"
  homepage "https://github.com/tyler-johnson/jog"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.3.0/jog_1.3.0_darwin_amd64.tar.gz"
      sha256 "3c11c8fbeafb9b776057337c38fe34ef724e6e4dd0bbdb7f58947ebbe34622a9"

      define_method(:install) do
        bin.install "jog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.3.0/jog_1.3.0_darwin_arm64.tar.gz"
      sha256 "f174151ab3c0a5296f119b0cad2525b811ea3ea77b7c016b538dec854cd02285"

      define_method(:install) do
        bin.install "jog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.3.0/jog_1.3.0_linux_amd64.tar.gz"
      sha256 "0e6de13133ec33933f878e6fe1c4b3c249a28eb67be6ff0e49a3b717ae985547"
      define_method(:install) do
        bin.install "jog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.3.0/jog_1.3.0_linux_arm64.tar.gz"
      sha256 "32ec23c21d85262545564f38a017a7f2634c105fe98ea204f53a71d40e5eefe4"
      define_method(:install) do
        bin.install "jog"
      end
    end
  end

  def caveats
    <<~EOS
      jog only snapshots when something invokes it. Wire the triggers:

        1. Shell alias (bash/zsh):  alias git='jog git'
        2. Agent hooks + skills:    jog agents install
        3. Editor save hooks:       jog editors install <editor>

      Then verify with:  jog doctor
    EOS
  end

  test do
    system bin/"jog", "version"
  end
end
