# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jog < Formula
  desc "Memory for your working tree - automatic git snapshots, jj-style"
  homepage "https://github.com/tyler-johnson/jog"
  version "1.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.7.1/jog_1.7.1_darwin_amd64.tar.gz"
      sha256 "460c5d4a256ab09f4a2e294652387adb40d443287cf7e4d09de3193e7a3618ad"

      define_method(:install) do
        bin.install "jog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.7.1/jog_1.7.1_darwin_arm64.tar.gz"
      sha256 "92eb1b5cba80b9a867a8971d614aec7f76f1419e0e1257f3951f8bf440094d33"

      define_method(:install) do
        bin.install "jog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.7.1/jog_1.7.1_linux_amd64.tar.gz"
      sha256 "68cc951016dc1ec7f0e049c9afbb049b9c16444d849fef1857900fea3cd96e31"
      define_method(:install) do
        bin.install "jog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyler-johnson/jog/releases/download/v1.7.1/jog_1.7.1_linux_arm64.tar.gz"
      sha256 "0b2ca01930ab92788b23234b4b19c5a1f53a7855fba59bf21498b8dde9796fa6"
      define_method(:install) do
        bin.install "jog"
      end
    end
  end

  def caveats
    <<~EOS
      jog only snapshots when something invokes it. Wire the triggers:

        jog install    # guided: the git alias, agent hooks, editor hooks

      or piece by piece: jog shell install, jog agents install,
      jog editors install <editor>. Then verify with:  jog doctor
    EOS
  end

  test do
    system bin/"jog", "version"
  end
end
